name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'  

      - name: Verify Go installation
        run: go version

      - name: Extract version from tag
        run: |
          echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF#refs/tags/}" =~ -alpha|-beta|-rc ]]; then
            echo "PRE_RELEASE=true" >> $GITHUB_ENV
          else
            echo "PRE_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Run Makefile to generate assets
        run: make all
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: List generated assets
        run: ls -lh builds/

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$PRE_RELEASE" = "true" ]; then
            gh release create "$PACKAGE_VERSION" builds/* --title "Release $PACKAGE_VERSION" --prerelease
          else
            gh release create "$PACKAGE_VERSION" builds/* --title "Release $PACKAGE_VERSION"
          fi