name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'  

      - name: Verify Go installation
        run: go version

      - name: Extract version from tag
        run: |
          echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF#refs/tags/}" =~ -alpha|-beta|-rc ]]; then
            echo "PRE_RELEASE=true" >> $GITHUB_ENV
          else
            echo "PRE_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Run Makefile to generate assets
        run: make all
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: List generated assets
        run: ls -lh builds/

      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRE_RELEASE: ${{ env.PRE_RELEASE }}
        with:
          args: builds/*